apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-networkpolicy
  namespace: aegis-system
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: aegis-control-plane
        - podSelector:
            matchLabels:
              app: aegis-audit-worker
      ports:
        - protocol: TCP
          port: 5432
  egress: []
