// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: snapshot/v1/snapshot.proto

package snapshotv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotDistributionService_StreamSnapshots_FullMethodName   = "/aegis.snapshot.v1.SnapshotDistributionService/StreamSnapshots"
	SnapshotDistributionService_GetActiveSnapshot_FullMethodName = "/aegis.snapshot.v1.SnapshotDistributionService/GetActiveSnapshot"
)

// SnapshotDistributionServiceClient is the client API for SnapshotDistributionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for streaming monotonic configuration snapshots and freshness leases
// from the Control Plane to Gateway replicas.
type SnapshotDistributionServiceClient interface {
	// Bidirectional stream: Control Plane pushes snapshots and leases;
	// Gateway streams acknowledgments and heartbeats.
	StreamSnapshots(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayMessage, ControlPlaneMessage], error)
	// Unary RPC for explicit snapshot fetch during gateway cold start
	GetActiveSnapshot(ctx context.Context, in *GetActiveSnapshotRequest, opts ...grpc.CallOption) (*SnapshotEnvelope, error)
}

type snapshotDistributionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotDistributionServiceClient(cc grpc.ClientConnInterface) SnapshotDistributionServiceClient {
	return &snapshotDistributionServiceClient{cc}
}

func (c *snapshotDistributionServiceClient) StreamSnapshots(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayMessage, ControlPlaneMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnapshotDistributionService_ServiceDesc.Streams[0], SnapshotDistributionService_StreamSnapshots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatewayMessage, ControlPlaneMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotDistributionService_StreamSnapshotsClient = grpc.BidiStreamingClient[GatewayMessage, ControlPlaneMessage]

func (c *snapshotDistributionServiceClient) GetActiveSnapshot(ctx context.Context, in *GetActiveSnapshotRequest, opts ...grpc.CallOption) (*SnapshotEnvelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotEnvelope)
	err := c.cc.Invoke(ctx, SnapshotDistributionService_GetActiveSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotDistributionServiceServer is the server API for SnapshotDistributionService service.
// All implementations must embed UnimplementedSnapshotDistributionServiceServer
// for forward compatibility.
//
// Service for streaming monotonic configuration snapshots and freshness leases
// from the Control Plane to Gateway replicas.
type SnapshotDistributionServiceServer interface {
	// Bidirectional stream: Control Plane pushes snapshots and leases;
	// Gateway streams acknowledgments and heartbeats.
	StreamSnapshots(grpc.BidiStreamingServer[GatewayMessage, ControlPlaneMessage]) error
	// Unary RPC for explicit snapshot fetch during gateway cold start
	GetActiveSnapshot(context.Context, *GetActiveSnapshotRequest) (*SnapshotEnvelope, error)
	mustEmbedUnimplementedSnapshotDistributionServiceServer()
}

// UnimplementedSnapshotDistributionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotDistributionServiceServer struct{}

func (UnimplementedSnapshotDistributionServiceServer) StreamSnapshots(grpc.BidiStreamingServer[GatewayMessage, ControlPlaneMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamSnapshots not implemented")
}
func (UnimplementedSnapshotDistributionServiceServer) GetActiveSnapshot(context.Context, *GetActiveSnapshotRequest) (*SnapshotEnvelope, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveSnapshot not implemented")
}
func (UnimplementedSnapshotDistributionServiceServer) mustEmbedUnimplementedSnapshotDistributionServiceServer() {
}
func (UnimplementedSnapshotDistributionServiceServer) testEmbeddedByValue() {}

// UnsafeSnapshotDistributionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotDistributionServiceServer will
// result in compilation errors.
type UnsafeSnapshotDistributionServiceServer interface {
	mustEmbedUnimplementedSnapshotDistributionServiceServer()
}

func RegisterSnapshotDistributionServiceServer(s grpc.ServiceRegistrar, srv SnapshotDistributionServiceServer) {
	// If the following call panics, it indicates UnimplementedSnapshotDistributionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotDistributionService_ServiceDesc, srv)
}

func _SnapshotDistributionService_StreamSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SnapshotDistributionServiceServer).StreamSnapshots(&grpc.GenericServerStream[GatewayMessage, ControlPlaneMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotDistributionService_StreamSnapshotsServer = grpc.BidiStreamingServer[GatewayMessage, ControlPlaneMessage]

func _SnapshotDistributionService_GetActiveSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotDistributionServiceServer).GetActiveSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotDistributionService_GetActiveSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotDistributionServiceServer).GetActiveSnapshot(ctx, req.(*GetActiveSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotDistributionService_ServiceDesc is the grpc.ServiceDesc for SnapshotDistributionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotDistributionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.snapshot.v1.SnapshotDistributionService",
	HandlerType: (*SnapshotDistributionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActiveSnapshot",
			Handler:    _SnapshotDistributionService_GetActiveSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSnapshots",
			Handler:       _SnapshotDistributionService_StreamSnapshots_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "snapshot/v1/snapshot.proto",
}
