// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: snapshot/v1/snapshot.proto

package snapshotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckStatus int32

const (
	AckStatus_ACK_STATUS_UNSPECIFIED AckStatus = 0
	AckStatus_ACK_STATUS_ACTIVATED   AckStatus = 1
	AckStatus_ACK_STATUS_REJECTED    AckStatus = 2
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_STATUS_UNSPECIFIED",
		1: "ACK_STATUS_ACTIVATED",
		2: "ACK_STATUS_REJECTED",
	}
	AckStatus_value = map[string]int32{
		"ACK_STATUS_UNSPECIFIED": 0,
		"ACK_STATUS_ACTIVATED":   1,
		"ACK_STATUS_REJECTED":    2,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_v1_snapshot_proto_enumTypes[0].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_snapshot_v1_snapshot_proto_enumTypes[0]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

// Top-level message sent from Control Plane to Gateway
type ControlPlaneMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlPlaneMessage_Snapshot
	//	*ControlPlaneMessage_Lease
	//	*ControlPlaneMessage_Ping
	Payload       isControlPlaneMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlaneMessage) Reset() {
	*x = ControlPlaneMessage{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneMessage) ProtoMessage() {}

func (x *ControlPlaneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneMessage.ProtoReflect.Descriptor instead.
func (*ControlPlaneMessage) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *ControlPlaneMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ControlPlaneMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ControlPlaneMessage) GetPayload() isControlPlaneMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlPlaneMessage) GetSnapshot() *SnapshotEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetLease() *FreshnessLease {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Lease); ok {
			return x.Lease
		}
	}
	return nil
}

func (x *ControlPlaneMessage) GetPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isControlPlaneMessage_Payload interface {
	isControlPlaneMessage_Payload()
}

type ControlPlaneMessage_Snapshot struct {
	Snapshot *SnapshotEnvelope `protobuf:"bytes,3,opt,name=snapshot,proto3,oneof"`
}

type ControlPlaneMessage_Lease struct {
	Lease *FreshnessLease `protobuf:"bytes,4,opt,name=lease,proto3,oneof"`
}

type ControlPlaneMessage_Ping struct {
	Ping *HeartbeatPing `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*ControlPlaneMessage_Snapshot) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_Lease) isControlPlaneMessage_Payload() {}

func (*ControlPlaneMessage_Ping) isControlPlaneMessage_Payload() {}

// Top-level message sent from Gateway to Control Plane
type GatewayMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	GatewayId string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayMessage_Ack
	//	*GatewayMessage_Pong
	Payload       isGatewayMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayMessage) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GatewayMessage) GetPayload() isGatewayMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetAck() *SnapshotAck {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *GatewayMessage) GetPong() *HeartbeatPong {
	if x != nil {
		if x, ok := x.Payload.(*GatewayMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isGatewayMessage_Payload interface {
	isGatewayMessage_Payload()
}

type GatewayMessage_Ack struct {
	Ack *SnapshotAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type GatewayMessage_Pong struct {
	Pong *HeartbeatPong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

func (*GatewayMessage_Ack) isGatewayMessage_Payload() {}

func (*GatewayMessage_Pong) isGatewayMessage_Payload() {}

// Monotonic signed configuration envelope
type SnapshotEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                  // Monotonic integer version
	SchemaVersion int32                  `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // Schema version (e.g. 1)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PayloadSha256 string                 `protobuf:"bytes,5,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"` // Hex-encoded SHA-256 of payload bytes
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                                  // Serialized SnapshotPayload bytes
	SigningKeyId  string                 `protobuf:"bytes,7,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`  // Identifier of control plane signing key
	Signature     []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                              // Ed25519 signature of payload_sha256
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnvelope) Reset() {
	*x = SnapshotEnvelope{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnvelope) ProtoMessage() {}

func (x *SnapshotEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnvelope.ProtoReflect.Descriptor instead.
func (*SnapshotEnvelope) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotEnvelope) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotEnvelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *SnapshotEnvelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SnapshotEnvelope) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SnapshotEnvelope) GetPayloadSha256() string {
	if x != nil {
		return x.PayloadSha256
	}
	return ""
}

func (x *SnapshotEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SnapshotEnvelope) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *SnapshotEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Unpacked configuration payload contained inside the envelope
type SnapshotPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Routes           []*RouteDefinition     `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	PolicyModules    []*PolicyModule        `protobuf:"bytes,3,rep,name=policy_modules,json=policyModules,proto3" json:"policy_modules,omitempty"`
	PolicyDataJson   []byte                 `protobuf:"bytes,4,opt,name=policy_data_json,json=policyDataJson,proto3" json:"policy_data_json,omitempty"` // JSON-encoded seed role and permission data
	IdentityMappings []*IdentityMapping     `protobuf:"bytes,5,rep,name=identity_mappings,json=identityMappings,proto3" json:"identity_mappings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotPayload) Reset() {
	*x = SnapshotPayload{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotPayload) ProtoMessage() {}

func (x *SnapshotPayload) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotPayload.ProtoReflect.Descriptor instead.
func (*SnapshotPayload) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotPayload) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotPayload) GetRoutes() []*RouteDefinition {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *SnapshotPayload) GetPolicyModules() []*PolicyModule {
	if x != nil {
		return x.PolicyModules
	}
	return nil
}

func (x *SnapshotPayload) GetPolicyDataJson() []byte {
	if x != nil {
		return x.PolicyDataJson
	}
	return nil
}

func (x *SnapshotPayload) GetIdentityMappings() []*IdentityMapping {
	if x != nil {
		return x.IdentityMappings
	}
	return nil
}

// Route definition mapping incoming HTTP requests to private upstream backends
type RouteDefinition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RouteId              string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`                              // Unique identifier, e.g. "orders.list"
	ServiceId            string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`                        // Destination service, e.g. "orders"
	HttpMethod           string                 `protobuf:"bytes,3,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`                     // GET, POST, PUT, DELETE, etc.
	PathTemplate         string                 `protobuf:"bytes,4,opt,name=path_template,json=pathTemplate,proto3" json:"path_template,omitempty"`               // Canonical template, e.g. "/api/orders"
	UpstreamUrl          string                 `protobuf:"bytes,5,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`                  // Target, e.g. "https://orders:8081"
	UpstreamSpiffeId     string                 `protobuf:"bytes,6,opt,name=upstream_spiffe_id,json=upstreamSpiffeId,proto3" json:"upstream_spiffe_id,omitempty"` // Expected server SAN: "spiffe://aegis.local/service/orders"
	RateLimit            *RateLimitPolicy       `protobuf:"bytes,7,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Timeout              *TimeoutPolicy         `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RequiresWorkloadMtls bool                   `protobuf:"varint,9,opt,name=requires_workload_mtls,json=requiresWorkloadMtls,proto3" json:"requires_workload_mtls,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RouteDefinition) Reset() {
	*x = RouteDefinition{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDefinition) ProtoMessage() {}

func (x *RouteDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDefinition.ProtoReflect.Descriptor instead.
func (*RouteDefinition) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *RouteDefinition) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RouteDefinition) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RouteDefinition) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *RouteDefinition) GetPathTemplate() string {
	if x != nil {
		return x.PathTemplate
	}
	return ""
}

func (x *RouteDefinition) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *RouteDefinition) GetUpstreamSpiffeId() string {
	if x != nil {
		return x.UpstreamSpiffeId
	}
	return ""
}

func (x *RouteDefinition) GetRateLimit() *RateLimitPolicy {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *RouteDefinition) GetTimeout() *TimeoutPolicy {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *RouteDefinition) GetRequiresWorkloadMtls() bool {
	if x != nil {
		return x.RequiresWorkloadMtls
	}
	return false
}

type RateLimitPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond int32                  `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	Burst             int32                  `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimitPolicy) Reset() {
	*x = RateLimitPolicy{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitPolicy) ProtoMessage() {}

func (x *RateLimitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitPolicy.ProtoReflect.Descriptor instead.
func (*RateLimitPolicy) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *RateLimitPolicy) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RateLimitPolicy) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type TimeoutPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestTimeoutMs  int32                  `protobuf:"varint,1,opt,name=request_timeout_ms,json=requestTimeoutMs,proto3" json:"request_timeout_ms,omitempty"`    // Default 15000ms
	UpstreamTimeoutMs int32                  `protobuf:"varint,2,opt,name=upstream_timeout_ms,json=upstreamTimeoutMs,proto3" json:"upstream_timeout_ms,omitempty"` // Default 5000ms
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimeoutPolicy) Reset() {
	*x = TimeoutPolicy{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutPolicy) ProtoMessage() {}

func (x *TimeoutPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutPolicy.ProtoReflect.Descriptor instead.
func (*TimeoutPolicy) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *TimeoutPolicy) GetRequestTimeoutMs() int32 {
	if x != nil {
		return x.RequestTimeoutMs
	}
	return 0
}

func (x *TimeoutPolicy) GetUpstreamTimeoutMs() int32 {
	if x != nil {
		return x.UpstreamTimeoutMs
	}
	return 0
}

type PolicyModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"` // e.g. "aegis.authz"
	ModuleName    string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`    // e.g. "rules.rego"
	SourceRego    string                 `protobuf:"bytes,3,opt,name=source_rego,json=sourceRego,proto3" json:"source_rego,omitempty"`    // Raw Rego v1 source code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyModule) Reset() {
	*x = PolicyModule{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyModule) ProtoMessage() {}

func (x *PolicyModule) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyModule.ProtoReflect.Descriptor instead.
func (*PolicyModule) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *PolicyModule) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PolicyModule) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *PolicyModule) GetSourceRego() string {
	if x != nil {
		return x.SourceRego
	}
	return ""
}

type IdentityMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`               // e.g. "developer"
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"` // e.g. ["orders.read", "payments.read"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityMapping) Reset() {
	*x = IdentityMapping{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityMapping) ProtoMessage() {}

func (x *IdentityMapping) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityMapping.ProtoReflect.Descriptor instead.
func (*IdentityMapping) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *IdentityMapping) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *IdentityMapping) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// 10-second freshness lease renewal issued by control plane
type FreshnessLease struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaseId         string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	SnapshotVersion int64                  `protobuf:"varint,2,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ValidUntil      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`             // Issued + 10s (fail-closed at valid_until + 50s)
	LeaseSignature  []byte                 `protobuf:"bytes,5,opt,name=lease_signature,json=leaseSignature,proto3" json:"lease_signature,omitempty"` // Ed25519 signature of lease metadata
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FreshnessLease) Reset() {
	*x = FreshnessLease{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreshnessLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreshnessLease) ProtoMessage() {}

func (x *FreshnessLease) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreshnessLease.ProtoReflect.Descriptor instead.
func (*FreshnessLease) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *FreshnessLease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *FreshnessLease) GetSnapshotVersion() int64 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *FreshnessLease) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *FreshnessLease) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *FreshnessLease) GetLeaseSignature() []byte {
	if x != nil {
		return x.LeaseSignature
	}
	return nil
}

// Gateway activation acknowledgment
type SnapshotAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayId      string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	ActiveVersion  int64                  `protobuf:"varint,2,opt,name=active_version,json=activeVersion,proto3" json:"active_version,omitempty"`
	Status         AckStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=aegis.snapshot.v1.AckStatus" json:"status,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AcknowledgedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=acknowledged_at,json=acknowledgedAt,proto3" json:"acknowledged_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnapshotAck) Reset() {
	*x = SnapshotAck{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAck) ProtoMessage() {}

func (x *SnapshotAck) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAck.ProtoReflect.Descriptor instead.
func (*SnapshotAck) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotAck) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *SnapshotAck) GetActiveVersion() int64 {
	if x != nil {
		return x.ActiveVersion
	}
	return 0
}

func (x *SnapshotAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_STATUS_UNSPECIFIED
}

func (x *SnapshotAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SnapshotAck) GetAcknowledgedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcknowledgedAt
	}
	return nil
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceId    string                 `protobuf:"bytes,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatPing) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceId    string                 `protobuf:"bytes,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	ActiveVersion int64                  `protobuf:"varint,2,opt,name=active_version,json=activeVersion,proto3" json:"active_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatPong) GetSequenceId() string {
	if x != nil {
		return x.SequenceId
	}
	return ""
}

func (x *HeartbeatPong) GetActiveVersion() int64 {
	if x != nil {
		return x.ActiveVersion
	}
	return 0
}

type GetActiveSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayId      string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	CurrentVersion int64                  `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetActiveSnapshotRequest) Reset() {
	*x = GetActiveSnapshotRequest{}
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSnapshotRequest) ProtoMessage() {}

func (x *GetActiveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_v1_snapshot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_v1_snapshot_proto_rawDescGZIP(), []int{13}
}

func (x *GetActiveSnapshotRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GetActiveSnapshotRequest) GetCurrentVersion() int64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

var File_snapshot_v1_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1asnapshot/v1/snapshot.proto\x12\x11aegis.snapshot.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\x13ControlPlaneMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12A\n" +
	"\bsnapshot\x18\x03 \x01(\v2#.aegis.snapshot.v1.SnapshotEnvelopeH\x00R\bsnapshot\x129\n" +
	"\x05lease\x18\x04 \x01(\v2!.aegis.snapshot.v1.FreshnessLeaseH\x00R\x05lease\x126\n" +
	"\x04ping\x18\x05 \x01(\v2 .aegis.snapshot.v1.HeartbeatPingH\x00R\x04pingB\t\n" +
	"\apayload\"\xe0\x01\n" +
	"\x0eGatewayMessage\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\x03ack\x18\x03 \x01(\v2\x1e.aegis.snapshot.v1.SnapshotAckH\x00R\x03ack\x126\n" +
	"\x04pong\x18\x04 \x01(\v2 .aegis.snapshot.v1.HeartbeatPongH\x00R\x04pongB\t\n" +
	"\apayload\"\xce\x02\n" +
	"\x10SnapshotEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\x05R\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12%\n" +
	"\x0epayload_sha256\x18\x05 \x01(\tR\rpayloadSha256\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12$\n" +
	"\x0esigning_key_id\x18\a \x01(\tR\fsigningKeyId\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\xaa\x02\n" +
	"\x0fSnapshotPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12:\n" +
	"\x06routes\x18\x02 \x03(\v2\".aegis.snapshot.v1.RouteDefinitionR\x06routes\x12F\n" +
	"\x0epolicy_modules\x18\x03 \x03(\v2\x1f.aegis.snapshot.v1.PolicyModuleR\rpolicyModules\x12(\n" +
	"\x10policy_data_json\x18\x04 \x01(\fR\x0epolicyDataJson\x12O\n" +
	"\x11identity_mappings\x18\x05 \x03(\v2\".aegis.snapshot.v1.IdentityMappingR\x10identityMappings\"\x97\x03\n" +
	"\x0fRouteDefinition\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vhttp_method\x18\x03 \x01(\tR\n" +
	"httpMethod\x12#\n" +
	"\rpath_template\x18\x04 \x01(\tR\fpathTemplate\x12!\n" +
	"\fupstream_url\x18\x05 \x01(\tR\vupstreamUrl\x12,\n" +
	"\x12upstream_spiffe_id\x18\x06 \x01(\tR\x10upstreamSpiffeId\x12A\n" +
	"\n" +
	"rate_limit\x18\a \x01(\v2\".aegis.snapshot.v1.RateLimitPolicyR\trateLimit\x12:\n" +
	"\atimeout\x18\b \x01(\v2 .aegis.snapshot.v1.TimeoutPolicyR\atimeout\x124\n" +
	"\x16requires_workload_mtls\x18\t \x01(\bR\x14requiresWorkloadMtls\"W\n" +
	"\x0fRateLimitPolicy\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\"m\n" +
	"\rTimeoutPolicy\x12,\n" +
	"\x12request_timeout_ms\x18\x01 \x01(\x05R\x10requestTimeoutMs\x12.\n" +
	"\x13upstream_timeout_ms\x18\x02 \x01(\x05R\x11upstreamTimeoutMs\"s\n" +
	"\fPolicyModule\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\x12\x1f\n" +
	"\vsource_rego\x18\x03 \x01(\tR\n" +
	"sourceRego\"G\n" +
	"\x0fIdentityMapping\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\xf5\x01\n" +
	"\x0eFreshnessLease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12)\n" +
	"\x10snapshot_version\x18\x02 \x01(\x03R\x0fsnapshotVersion\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12;\n" +
	"\vvalid_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x12'\n" +
	"\x0flease_signature\x18\x05 \x01(\fR\x0eleaseSignature\"\xf3\x01\n" +
	"\vSnapshotAck\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12%\n" +
	"\x0eactive_version\x18\x02 \x01(\x03R\ractiveVersion\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.aegis.snapshot.v1.AckStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12C\n" +
	"\x0facknowledged_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eacknowledgedAt\"0\n" +
	"\rHeartbeatPing\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\tR\n" +
	"sequenceId\"W\n" +
	"\rHeartbeatPong\x12\x1f\n" +
	"\vsequence_id\x18\x01 \x01(\tR\n" +
	"sequenceId\x12%\n" +
	"\x0eactive_version\x18\x02 \x01(\x03R\ractiveVersion\"b\n" +
	"\x18GetActiveSnapshotRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\x03R\x0ecurrentVersion*Z\n" +
	"\tAckStatus\x12\x1a\n" +
	"\x16ACK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACK_STATUS_ACTIVATED\x10\x01\x12\x17\n" +
	"\x13ACK_STATUS_REJECTED\x10\x022\xe6\x01\n" +
	"\x1bSnapshotDistributionService\x12`\n" +
	"\x0fStreamSnapshots\x12!.aegis.snapshot.v1.GatewayMessage\x1a&.aegis.snapshot.v1.ControlPlaneMessage(\x010\x01\x12e\n" +
	"\x11GetActiveSnapshot\x12+.aegis.snapshot.v1.GetActiveSnapshotRequest\x1a#.aegis.snapshot.v1.SnapshotEnvelopeB&Z$aegis/pkg/api/snapshot/v1;snapshotv1b\x06proto3"

var (
	file_snapshot_v1_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_v1_snapshot_proto_rawDescData []byte
)

func file_snapshot_v1_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_v1_snapshot_proto_rawDesc), len(file_snapshot_v1_snapshot_proto_rawDesc)))
	})
	return file_snapshot_v1_snapshot_proto_rawDescData
}

var file_snapshot_v1_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_snapshot_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_snapshot_v1_snapshot_proto_goTypes = []any{
	(AckStatus)(0),                   // 0: aegis.snapshot.v1.AckStatus
	(*ControlPlaneMessage)(nil),      // 1: aegis.snapshot.v1.ControlPlaneMessage
	(*GatewayMessage)(nil),           // 2: aegis.snapshot.v1.GatewayMessage
	(*SnapshotEnvelope)(nil),         // 3: aegis.snapshot.v1.SnapshotEnvelope
	(*SnapshotPayload)(nil),          // 4: aegis.snapshot.v1.SnapshotPayload
	(*RouteDefinition)(nil),          // 5: aegis.snapshot.v1.RouteDefinition
	(*RateLimitPolicy)(nil),          // 6: aegis.snapshot.v1.RateLimitPolicy
	(*TimeoutPolicy)(nil),            // 7: aegis.snapshot.v1.TimeoutPolicy
	(*PolicyModule)(nil),             // 8: aegis.snapshot.v1.PolicyModule
	(*IdentityMapping)(nil),          // 9: aegis.snapshot.v1.IdentityMapping
	(*FreshnessLease)(nil),           // 10: aegis.snapshot.v1.FreshnessLease
	(*SnapshotAck)(nil),              // 11: aegis.snapshot.v1.SnapshotAck
	(*HeartbeatPing)(nil),            // 12: aegis.snapshot.v1.HeartbeatPing
	(*HeartbeatPong)(nil),            // 13: aegis.snapshot.v1.HeartbeatPong
	(*GetActiveSnapshotRequest)(nil), // 14: aegis.snapshot.v1.GetActiveSnapshotRequest
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_snapshot_v1_snapshot_proto_depIdxs = []int32{
	15, // 0: aegis.snapshot.v1.ControlPlaneMessage.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 1: aegis.snapshot.v1.ControlPlaneMessage.snapshot:type_name -> aegis.snapshot.v1.SnapshotEnvelope
	10, // 2: aegis.snapshot.v1.ControlPlaneMessage.lease:type_name -> aegis.snapshot.v1.FreshnessLease
	12, // 3: aegis.snapshot.v1.ControlPlaneMessage.ping:type_name -> aegis.snapshot.v1.HeartbeatPing
	15, // 4: aegis.snapshot.v1.GatewayMessage.timestamp:type_name -> google.protobuf.Timestamp
	11, // 5: aegis.snapshot.v1.GatewayMessage.ack:type_name -> aegis.snapshot.v1.SnapshotAck
	13, // 6: aegis.snapshot.v1.GatewayMessage.pong:type_name -> aegis.snapshot.v1.HeartbeatPong
	15, // 7: aegis.snapshot.v1.SnapshotEnvelope.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: aegis.snapshot.v1.SnapshotEnvelope.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 9: aegis.snapshot.v1.SnapshotPayload.routes:type_name -> aegis.snapshot.v1.RouteDefinition
	8,  // 10: aegis.snapshot.v1.SnapshotPayload.policy_modules:type_name -> aegis.snapshot.v1.PolicyModule
	9,  // 11: aegis.snapshot.v1.SnapshotPayload.identity_mappings:type_name -> aegis.snapshot.v1.IdentityMapping
	6,  // 12: aegis.snapshot.v1.RouteDefinition.rate_limit:type_name -> aegis.snapshot.v1.RateLimitPolicy
	7,  // 13: aegis.snapshot.v1.RouteDefinition.timeout:type_name -> aegis.snapshot.v1.TimeoutPolicy
	15, // 14: aegis.snapshot.v1.FreshnessLease.issued_at:type_name -> google.protobuf.Timestamp
	15, // 15: aegis.snapshot.v1.FreshnessLease.valid_until:type_name -> google.protobuf.Timestamp
	0,  // 16: aegis.snapshot.v1.SnapshotAck.status:type_name -> aegis.snapshot.v1.AckStatus
	15, // 17: aegis.snapshot.v1.SnapshotAck.acknowledged_at:type_name -> google.protobuf.Timestamp
	2,  // 18: aegis.snapshot.v1.SnapshotDistributionService.StreamSnapshots:input_type -> aegis.snapshot.v1.GatewayMessage
	14, // 19: aegis.snapshot.v1.SnapshotDistributionService.GetActiveSnapshot:input_type -> aegis.snapshot.v1.GetActiveSnapshotRequest
	1,  // 20: aegis.snapshot.v1.SnapshotDistributionService.StreamSnapshots:output_type -> aegis.snapshot.v1.ControlPlaneMessage
	3,  // 21: aegis.snapshot.v1.SnapshotDistributionService.GetActiveSnapshot:output_type -> aegis.snapshot.v1.SnapshotEnvelope
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_snapshot_v1_snapshot_proto_init() }
func file_snapshot_v1_snapshot_proto_init() {
	if File_snapshot_v1_snapshot_proto != nil {
		return
	}
	file_snapshot_v1_snapshot_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlPlaneMessage_Snapshot)(nil),
		(*ControlPlaneMessage_Lease)(nil),
		(*ControlPlaneMessage_Ping)(nil),
	}
	file_snapshot_v1_snapshot_proto_msgTypes[1].OneofWrappers = []any{
		(*GatewayMessage_Ack)(nil),
		(*GatewayMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_v1_snapshot_proto_rawDesc), len(file_snapshot_v1_snapshot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshot_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_v1_snapshot_proto_depIdxs,
		EnumInfos:         file_snapshot_v1_snapshot_proto_enumTypes,
		MessageInfos:      file_snapshot_v1_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_v1_snapshot_proto = out.File
	file_snapshot_v1_snapshot_proto_goTypes = nil
	file_snapshot_v1_snapshot_proto_depIdxs = nil
}
