// Package controlv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package controlv1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AuditEventDecision.
const (
	AuditEventDecisionAllow AuditEventDecision = "allow"
	AuditEventDecisionDeny  AuditEventDecision = "deny"
)

// Defines values for AuditEventEventType.
const (
	Completion AuditEventEventType = "completion"
	Decision   AuditEventEventType = "decision"
	Denial     AuditEventEventType = "denial"
)

// Defines values for AuditEventPrincipalKind.
const (
	Anonymous AuditEventPrincipalKind = "anonymous"
	User      AuditEventPrincipalKind = "user"
	Workload  AuditEventPrincipalKind = "workload"
)

// Defines values for GatewayStatusStatus.
const (
	Degraded    GatewayStatusStatus = "degraded"
	Healthy     GatewayStatusStatus = "healthy"
	Partitioned GatewayStatusStatus = "partitioned"
)

// Defines values for QuarantineRecordStatus.
const (
	Active  QuarantineRecordStatus = "active"
	Expired QuarantineRecordStatus = "expired"
	Revoked QuarantineRecordStatus = "revoked"
)

// Defines values for RouteHttpMethod.
const (
	RouteHttpMethodDELETE  RouteHttpMethod = "DELETE"
	RouteHttpMethodGET     RouteHttpMethod = "GET"
	RouteHttpMethodHEAD    RouteHttpMethod = "HEAD"
	RouteHttpMethodOPTIONS RouteHttpMethod = "OPTIONS"
	RouteHttpMethodPATCH   RouteHttpMethod = "PATCH"
	RouteHttpMethodPOST    RouteHttpMethod = "POST"
	RouteHttpMethodPUT     RouteHttpMethod = "PUT"
)

// Defines values for RouteCreateRequestHttpMethod.
const (
	RouteCreateRequestHttpMethodDELETE  RouteCreateRequestHttpMethod = "DELETE"
	RouteCreateRequestHttpMethodGET     RouteCreateRequestHttpMethod = "GET"
	RouteCreateRequestHttpMethodHEAD    RouteCreateRequestHttpMethod = "HEAD"
	RouteCreateRequestHttpMethodOPTIONS RouteCreateRequestHttpMethod = "OPTIONS"
	RouteCreateRequestHttpMethodPATCH   RouteCreateRequestHttpMethod = "PATCH"
	RouteCreateRequestHttpMethodPOST    RouteCreateRequestHttpMethod = "POST"
	RouteCreateRequestHttpMethodPUT     RouteCreateRequestHttpMethod = "PUT"
)

// Defines values for ListAuditEventsParamsDecision.
const (
	ListAuditEventsParamsDecisionAllow ListAuditEventsParamsDecision = "allow"
	ListAuditEventsParamsDecisionDeny  ListAuditEventsParamsDecision = "deny"
)

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Decision        AuditEventDecision       `json:"decision"`
	DurationMs      *int                     `json:"duration_ms,omitempty"`
	EventId         openapi_types.UUID       `json:"event_id"`
	EventType       AuditEventEventType      `json:"event_type"`
	HttpMethod      *string                  `json:"http_method,omitempty"`
	PrincipalId     string                   `json:"principal_id"`
	PrincipalKind   *AuditEventPrincipalKind `json:"principal_kind,omitempty"`
	ReasonCode      string                   `json:"reason_code"`
	RequestId       openapi_types.UUID       `json:"request_id"`
	RequestPath     *string                  `json:"request_path,omitempty"`
	Roles           *[]string                `json:"roles,omitempty"`
	RouteId         string                   `json:"route_id"`
	ServiceId       string                   `json:"service_id"`
	SnapshotVersion int64                    `json:"snapshot_version"`
	StatusCode      *int                     `json:"status_code,omitempty"`
	Timestamp       time.Time                `json:"timestamp"`
}

// AuditEventDecision defines model for AuditEvent.Decision.
type AuditEventDecision string

// AuditEventEventType defines model for AuditEvent.EventType.
type AuditEventEventType string

// AuditEventPrincipalKind defines model for AuditEvent.PrincipalKind.
type AuditEventPrincipalKind string

// AuditEventListResponse defines model for AuditEventListResponse.
type AuditEventListResponse struct {
	Events     []AuditEvent `json:"events"`
	NextCursor *string      `json:"next_cursor,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      string                  `json:"code"`
	Details   *map[string]interface{} `json:"details,omitempty"`
	Message   string                  `json:"message"`
	RequestId openapi_types.UUID      `json:"request_id"`
	Timestamp time.Time               `json:"timestamp"`
}

// GatewayListResponse defines model for GatewayListResponse.
type GatewayListResponse struct {
	Gateways []GatewayStatus `json:"gateways"`
}

// GatewayStatus defines model for GatewayStatus.
type GatewayStatus struct {
	ActiveVersion   int64               `json:"active_version"`
	ConnectedAt     time.Time           `json:"connected_at"`
	GatewayId       string              `json:"gateway_id"`
	LastHeartbeatAt *time.Time          `json:"last_heartbeat_at,omitempty"`
	LeaseExpiresAt  *time.Time          `json:"lease_expires_at,omitempty"`
	Status          GatewayStatusStatus `json:"status"`
}

// GatewayStatusStatus defines model for GatewayStatus.Status.
type GatewayStatusStatus string

// PolicyCreateRequest defines model for PolicyCreateRequest.
type PolicyCreateRequest struct {
	Name       string `json:"name"`
	PolicyId   string `json:"policy_id"`
	SourceRego string `json:"source_rego"`
}

// PolicyDraft defines model for PolicyDraft.
type PolicyDraft struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Name       string     `json:"name"`
	PolicyId   string     `json:"policy_id"`
	SourceRego string     `json:"source_rego"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// PolicyPublishRequest defines model for PolicyPublishRequest.
type PolicyPublishRequest struct {
	Comment *string `json:"comment,omitempty"`
}

// PolicyPublishResponse defines model for PolicyPublishResponse.
type PolicyPublishResponse struct {
	PublishedAt     time.Time `json:"published_at"`
	SigningKeyId    string    `json:"signing_key_id"`
	SnapshotVersion int64     `json:"snapshot_version"`
}

// PolicyRollbackRequest defines model for PolicyRollbackRequest.
type PolicyRollbackRequest struct {
	Comment         *string `json:"comment,omitempty"`
	TargetVersionId string  `json:"target_version_id"`
}

// PolicySimulationRequest defines model for PolicySimulationRequest.
type PolicySimulationRequest struct {
	CandidateRego *string                `json:"candidate_rego,omitempty"`
	InputContext  map[string]interface{} `json:"input_context"`
}

// PolicySimulationResponse defines model for PolicySimulationResponse.
type PolicySimulationResponse struct {
	Allow       bool                    `json:"allow"`
	Diagnostics *map[string]interface{} `json:"diagnostics,omitempty"`
	DurationUs  int                     `json:"duration_us"`
	ReasonCode  string                  `json:"reason_code"`
}

// PolicyValidationRequest defines model for PolicyValidationRequest.
type PolicyValidationRequest struct {
	CandidateRego *string `json:"candidate_rego,omitempty"`
}

// PolicyValidationResponse defines model for PolicyValidationResponse.
type PolicyValidationResponse struct {
	Errors      *[]string `json:"errors,omitempty"`
	FailedCount int       `json:"failed_count"`
	PassedCount int       `json:"passed_count"`
	TestCount   int       `json:"test_count"`
	Valid       bool      `json:"valid"`
}

// PolicyVersion defines model for PolicyVersion.
type PolicyVersion struct {
	PolicyId        string    `json:"policy_id"`
	PublishedAt     time.Time `json:"published_at"`
	PublishedBy     string    `json:"published_by"`
	SnapshotVersion int64     `json:"snapshot_version"`
	SourceRego      string    `json:"source_rego"`
	VersionId       string    `json:"version_id"`
}

// PolicyVersionListResponse defines model for PolicyVersionListResponse.
type PolicyVersionListResponse struct {
	NextCursor *string         `json:"next_cursor,omitempty"`
	Versions   []PolicyVersion `json:"versions"`
}

// QuarantineRecord defines model for QuarantineRecord.
type QuarantineRecord struct {
	Actor         *string                `json:"actor,omitempty"`
	ExpiresAt     *time.Time             `json:"expires_at,omitempty"`
	PrincipalId   string                 `json:"principal_id"`
	QuarantinedAt time.Time              `json:"quarantined_at"`
	Reason        string                 `json:"reason"`
	Status        QuarantineRecordStatus `json:"status"`
}

// QuarantineRecordStatus defines model for QuarantineRecord.Status.
type QuarantineRecordStatus string

// QuarantineRequest defines model for QuarantineRequest.
type QuarantineRequest struct {
	Actor     *string    `json:"actor,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Reason    string     `json:"reason"`
}

// Route defines model for Route.
type Route struct {
	CreatedAt            *time.Time      `json:"created_at,omitempty"`
	HttpMethod           RouteHttpMethod `json:"http_method"`
	PathTemplate         string          `json:"path_template"`
	RateLimitBurst       *int            `json:"rate_limit_burst,omitempty"`
	RateLimitRps         *int            `json:"rate_limit_rps,omitempty"`
	RequiresWorkloadMtls *bool           `json:"requires_workload_mtls,omitempty"`
	RouteId              string          `json:"route_id"`
	ServiceId            string          `json:"service_id"`
	TimeoutMs            *int            `json:"timeout_ms,omitempty"`
	UpdatedAt            *time.Time      `json:"updated_at,omitempty"`
	UpstreamSpiffeId     *string         `json:"upstream_spiffe_id,omitempty"`
	UpstreamUrl          string          `json:"upstream_url"`
}

// RouteHttpMethod defines model for Route.HttpMethod.
type RouteHttpMethod string

// RouteCreateRequest defines model for RouteCreateRequest.
type RouteCreateRequest struct {
	HttpMethod           RouteCreateRequestHttpMethod `json:"http_method"`
	PathTemplate         string                       `json:"path_template"`
	RateLimitBurst       *int                         `json:"rate_limit_burst,omitempty"`
	RateLimitRps         *int                         `json:"rate_limit_rps,omitempty"`
	RequiresWorkloadMtls *bool                        `json:"requires_workload_mtls,omitempty"`
	RouteId              string                       `json:"route_id"`
	ServiceId            string                       `json:"service_id"`
	TimeoutMs            *int                         `json:"timeout_ms,omitempty"`
	UpstreamSpiffeId     *string                      `json:"upstream_spiffe_id,omitempty"`
	UpstreamUrl          string                       `json:"upstream_url"`
}

// RouteCreateRequestHttpMethod defines model for RouteCreateRequest.HttpMethod.
type RouteCreateRequestHttpMethod string

// RouteListResponse defines model for RouteListResponse.
type RouteListResponse struct {
	NextCursor *string `json:"next_cursor,omitempty"`
	Routes     []Route `json:"routes"`
}

// UnquarantineRequest defines model for UnquarantineRequest.
type UnquarantineRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// UnquarantineResponse defines model for UnquarantineResponse.
type UnquarantineResponse struct {
	PrincipalId     string    `json:"principal_id"`
	UnquarantinedAt time.Time `json:"unquarantined_at"`
}

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PreconditionFailed defines model for PreconditionFailed.
type PreconditionFailed = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	PrincipalId   *string                        `form:"principal_id,omitempty" json:"principal_id,omitempty"`
	ServiceId     *string                        `form:"service_id,omitempty" json:"service_id,omitempty"`
	Decision      *ListAuditEventsParamsDecision `form:"decision,omitempty" json:"decision,omitempty"`
	FromTimestamp *time.Time                     `form:"from_timestamp,omitempty" json:"from_timestamp,omitempty"`
	ToTimestamp   *time.Time                     `form:"to_timestamp,omitempty" json:"to_timestamp,omitempty"`

	// Cursor Opaque pagination cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of records to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAuditEventsParamsDecision defines parameters for ListAuditEvents.
type ListAuditEventsParamsDecision string

// ListGatewaysParams defines parameters for ListGateways.
type ListGatewaysParams struct {
	// Cursor Opaque pagination cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of records to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePolicyDraftParams defines parameters for CreatePolicyDraft.
type CreatePolicyDraftParams struct {
	// IdempotencyKey Client-provided UUID to ensure idempotent execution.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// PublishPolicyParams defines parameters for PublishPolicy.
type PublishPolicyParams struct {
	// IfMatch Optimistic concurrency control ETag.
	IfMatch *IfMatch `json:"If-Match,omitempty"`

	// IdempotencyKey Client-provided UUID to ensure idempotent execution.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// RollbackPolicyParams defines parameters for RollbackPolicy.
type RollbackPolicyParams struct {
	// IfMatch Optimistic concurrency control ETag.
	IfMatch *IfMatch `json:"If-Match,omitempty"`

	// IdempotencyKey Client-provided UUID to ensure idempotent execution.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetPolicyVersionsParams defines parameters for GetPolicyVersions.
type GetPolicyVersionsParams struct {
	// Cursor Opaque pagination cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of records to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// UnquarantinePrincipalParams defines parameters for UnquarantinePrincipal.
type UnquarantinePrincipalParams struct {
	// IdempotencyKey Client-provided UUID to ensure idempotent execution.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// QuarantinePrincipalParams defines parameters for QuarantinePrincipal.
type QuarantinePrincipalParams struct {
	// IdempotencyKey Client-provided UUID to ensure idempotent execution.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListRoutesParams defines parameters for ListRoutes.
type ListRoutesParams struct {
	// Cursor Opaque pagination cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of records to return.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateRouteParams defines parameters for CreateRoute.
type CreateRouteParams struct {
	// IdempotencyKey Client-provided UUID to ensure idempotent execution.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreatePolicyDraftJSONRequestBody defines body for CreatePolicyDraft for application/json ContentType.
type CreatePolicyDraftJSONRequestBody = PolicyCreateRequest

// PublishPolicyJSONRequestBody defines body for PublishPolicy for application/json ContentType.
type PublishPolicyJSONRequestBody = PolicyPublishRequest

// RollbackPolicyJSONRequestBody defines body for RollbackPolicy for application/json ContentType.
type RollbackPolicyJSONRequestBody = PolicyRollbackRequest

// SimulatePolicyJSONRequestBody defines body for SimulatePolicy for application/json ContentType.
type SimulatePolicyJSONRequestBody = PolicySimulationRequest

// ValidatePolicyJSONRequestBody defines body for ValidatePolicy for application/json ContentType.
type ValidatePolicyJSONRequestBody = PolicyValidationRequest

// UnquarantinePrincipalJSONRequestBody defines body for UnquarantinePrincipal for application/json ContentType.
type UnquarantinePrincipalJSONRequestBody = UnquarantineRequest

// QuarantinePrincipalJSONRequestBody defines body for QuarantinePrincipal for application/json ContentType.
type QuarantinePrincipalJSONRequestBody = QuarantineRequest

// CreateRouteJSONRequestBody defines body for CreateRoute for application/json ContentType.
type CreateRouteJSONRequestBody = RouteCreateRequest
